theme: jekyll-theme-cayman
title: Ryan Geary
description: Computer Engineering Major at the University of Delaware minoring in Cybersecurity and Computer Science. Interested in secure software, POSIX compliancy, Vim, reverse engineering, i3wm, and more.
